var facts = [
   'My favorite color is cyan!',
   'I\'m an introvert kid.',
   'There are a total of 4 easter eggs!',
   'I don\'t like to socialize a lot.',
   'I have been a developer at least for 2 years now!',
   'Do you see that rotate button on the homepage?',
   'My Discord username is Awish#6969',
   'I use the word "interesting" a lot!',
   'My music genres are EDM, future bass, retro and synth!',
   'Beep Boop',
   'No U',
   'Error',
   'I like making food',
   'I code 24/7!',
   'Don\'t you think the avatar in the footer is odd?',
   'Hello again!',
   'Am an idiot',
   '👀',
   'Am out of Fun Facts now :(',
   'Send help!',
   'Please just turn off your autocorrect',
   '<i>Runs</i>',
   'Once upon a time...',
   'Hello darkness my old friend. I\'ve come to see you again.',
   'Pain',
   'You wish?',
   '<i>Laughs</i>',
   '<i>Dies</i>',
   'You didn\'t read the previous fact, right?'
]
